export const CE_SKILL_RESOURCE_GUIDANCE_MARKER = "<!-- pi-compound-engineering:skill-resource-guidance -->";

const CE_SKILL_PROMPT_PATTERN = /(?:^|\s)\/(?:skill:)?ce-[a-z0-9-]*\b|pi-compound-engineering\/skills\/ce-[a-z0-9-]+/i;

export interface CeSkillResourceGuidanceSkill {
	name: string;
	filePath?: string;
	baseDir?: string;
}

/**
 * Render the short system-prompt appendix that teaches Pi agents how to
 * resolve bundled resources for skills generated by this package.
 *
 * The guidance always includes the stable package-relative layout. When the
 * extension passes the current package root, it also includes an absolute
 * command example so shell calls do not depend on the project cwd.
 */
export function renderCeSkillResourceGuidance(packageRoot?: string): string {
	const lines = [
		CE_SKILL_RESOURCE_GUIDANCE_MARKER,
		"## Compound Engineering skill resources in Pi",
		"",
		"Skills from `pi-compound-engineering` may reference bundled `scripts/`, `references/`, or `assets/` paths. Resolve those paths relative to that skill's generated package directory, not the project cwd.",
		"",
		"Path rule: `scripts/<file>` -> `skills/<skill-name>/scripts/<file>`; `references/<file>` -> `skills/<skill-name>/references/<file>`; `assets/<file>` -> `skills/<skill-name>/assets/<file>`.",
	];

	if (packageRoot) {
		lines.push(
			"",
			`Package install directory for this session: \`${packageRoot}\`. For shell commands, use this absolute package path so commands do not depend on the project cwd.`,
			`For any Compound Engineering (CE) skill, map resources to \`${packageRoot}/skills/<skill-name>/...\` before reading or executing them: \`scripts/<file>\`, \`references/<file>\`, and \`assets/<file>\` live under that skill directory.`,
			`Use \`${packageRoot}/package.json\` for the package manifest. Do not look for Claude-only \`${packageRoot}/plugin.json\` or package-root \`${packageRoot}/scripts/<file>\`; those are not Pi package resources.`,
			`Example: \`/ce-setup\` uses \`${packageRoot}/skills/ce-setup/scripts/check-health\` and \`${packageRoot}/skills/ce-setup/references/config-template.yaml\`.`,
		);
	} else {
		lines.push(
			"",
			"Example: for any Compound Engineering (CE) skill invoked as `/ce-<skill>`, resolve `scripts/<file>` as `skills/ce-<skill>/scripts/<file>` and `references/<file>` as `skills/ce-<skill>/references/<file>`. For `/ce-setup`, the health check is `skills/ce-setup/scripts/check-health`.",
		);
	}

	return lines.join("\n");
}

/**
 * Return true when the current prompt or loaded skill list indicates that a
 * Compound Engineering skill can run. Natural-language invocations may rely
 * on the available skills list rather than an explicit `/ce-*` command, so
 * check both surfaces.
 */
export function shouldAppendCeSkillResourceGuidance(
	prompt: string,
	skills: CeSkillResourceGuidanceSkill[] | undefined = undefined,
): boolean {
	return CE_SKILL_PROMPT_PATTERN.test(prompt) || hasLoadedCompoundEngineeringSkills(skills);
}

function hasLoadedCompoundEngineeringSkills(skills: CeSkillResourceGuidanceSkill[] | undefined): boolean {
	return skills?.some((skill) => {
		if (/^ce-[a-z0-9-]+$/.test(skill.name)) return true;
		return [skill.filePath, skill.baseDir].some((path) => path?.includes("pi-compound-engineering"));
	}) ?? false;
}

/**
 * Append CE resource guidance exactly once to a system prompt string.
 */
export function appendCeSkillResourceGuidance(systemPrompt: string, packageRoot?: string): string {
	if (systemPrompt.includes(CE_SKILL_RESOURCE_GUIDANCE_MARKER)) {
		return systemPrompt;
	}
	const guidance = renderCeSkillResourceGuidance(packageRoot);
	const trimmedPrompt = systemPrompt.trimEnd();
	return trimmedPrompt.length > 0 ? `${trimmedPrompt}\n\n${guidance}` : guidance;
}
