#!/usr/bin/env node
// @ts-check
/**
 * `postinstall` entry point. Reads the staging dir path left behind by
 * `preinstall` (`scripts/stage.mjs`) and moves the converted `skills/`,
 * `agents/`, and `THIRD-PARTY-NOTICES` into the final install dir.
 *
 * Failure modes:
 *
 * - The staging path file is missing → `preinstall` was skipped (e.g.
 *   `npm install --ignore-scripts`) or was killed mid-run. Exit 0; the
 *   extension's skipped-postinstall warning will fire on the next Pi
 *   launch and the user can recover by re-running `pi install` (the
 *   lifecycle is idempotent).
 *
 * - The staging dir no longer exists → same recovery path.
 *
 * - The commit rename fails → exit non-zero. The user gets a clear error
 *   and can retry. The previous install's `skills/`, `agents/`, and
 *   `THIRD-PARTY-NOTICES` are still on disk (they were generated by
 *   the previous install, not committed), so we back them up to
 *   `.previous-<timestamp>/` before the swap and restore on failure
 *   to avoid a half-updated install.
 */

import { existsSync } from "node:fs";
import { cp, mkdir, readdir, readFile, rename, rm } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_ROOT = dirname(fileURLToPath(import.meta.url)) + "/..";
const STAGING_BASE_DIR = join(homedir(), ".pi-compound-engineering-staging");
const STAGING_PATH_FILE = join(STAGING_BASE_DIR, "staging-path.txt");
const RECOVERY_INSTRUCTION =
	"Re-run `pi install npm:pi-compound-engineering` (without --ignore-scripts) and restart Pi.";

function log(message) {
	process.stderr.write(`[pi-compound-engineering] ${message}\n`);
}

function warn(message) {
	process.stderr.write(`[pi-compound-engineering] WARN: ${message}\n`);
}

/**
 * Move `src` to `dest`. On the happy path this is `fs.rename`, which is
 * atomic. If `src` and `dest` are on different filesystems `rename`
 * fails with `EXDEV`; fall back to a recursive copy + remove so the
 * install works on systems where the staging dir (under the user's
 * home) is on a different mount than the npm package directory.
 *
 * @param {string} src
 * @param {string} dest
 */
async function moveAcrossFilesystems(src, dest) {
	try {
		await rename(src, dest);
	} catch (err) {
		if (err && /** @type {any} */ (err).code === "EXDEV") {
			await cp(src, dest, { recursive: true });
			await rm(src, { recursive: true, force: true });
		} else {
			throw err;
		}
	}
}

/**
 * Read the staging path left behind by the matching preinstall run.
 * The handoff file lives at a fixed path under
 * `~/.pi-compound-engineering-staging/` (not under `os.tmpdir()`) so
 * the CodeQL `js/insecure-temporary-file` rule does not flag the read
 * or the write.
 *
 * @returns {Promise<string | null>}
 */
async function readStagingPath() {
	if (!existsSync(STAGING_PATH_FILE)) return null;
	try {
		const raw = await readFile(STAGING_PATH_FILE, "utf8");
		const trimmed = raw.trim();
		return trimmed.length > 0 ? trimmed : null;
	} catch {
		return null;
	}
}

async function main() {
	const stagingDir = await readStagingPath();
	if (!stagingDir) {
		warn(`Staging path file is missing. preinstall was skipped or killed mid-run. ${RECOVERY_INSTRUCTION}`);
		process.exit(0);
	}
	if (!existsSync(stagingDir)) {
		warn(`Staging dir no longer exists: ${stagingDir}. ${RECOVERY_INSTRUCTION}`);
		await rm(STAGING_PATH_FILE, { force: true });
		process.exit(0);
	}

	const outputDir = join(stagingDir, "output");
	if (!existsSync(outputDir)) {
		warn(`Staging output dir is missing: ${outputDir}. ${RECOVERY_INSTRUCTION}`);
		await rm(stagingDir, { recursive: true, force: true });
		await rm(STAGING_PATH_FILE, { force: true });
		process.exit(0);
	}

	const productionSkillsDir = join(PACKAGE_ROOT, "skills");
	const productionAgentsDir = join(PACKAGE_ROOT, "agents");
	const productionNotices = join(PACKAGE_ROOT, "THIRD-PARTY-NOTICES");

	const stagingNotices = join(outputDir, "THIRD-PARTY-NOTICES");
	const stagingSkills = join(outputDir, "skills");
	const stagingAgents = join(outputDir, "agents");

	if (!existsSync(stagingNotices)) {
		warn(`Staged THIRD-PARTY-NOTICES is missing: ${stagingNotices}.`);
	}
	if (!existsSync(stagingSkills) || !existsSync(stagingAgents)) {
		warn(`Staged skills/agents are missing in: ${outputDir}.`);
	}

	// Move the staged content into place. We rename in the order
	// THIRD-PARTY-NOTICES, skills, agents so the install dir always
	// contains a coherent state.
	//
	// The backup path is mostly belt-and-braces:
	//
	// - A `git clone && npm install` (no previous install) has nothing
	//   to back up; `backupIfExists` is a no-op for every entry.
	// - A real `npm install pi-compound-engineering@<new>` (update)
	//   removes the package dir before unpacking the new version, so
	//   the previous version's gitignored `skills/` and `agents/`
	//   are already gone by the time this script runs. The backup
	//   branch is also a no-op there.
	// - The backup is meaningful only when this script runs against an
	//   install dir that still has a previous version on disk (e.g.
	//   the user manually re-invoked the preinstall, or in a dev
	//   workflow where the package dir is checked out as a regular
	//   tree). In that case we move the previous content to
	//   `.previous-<timestamp>/` first, then rename the staged
	//   content into place, then remove the backup on success or
	//   restore from it on failure. `backupIfExists` is a no-op when
	//   there is no previous content.
	const backupRoot = join(PACKAGE_ROOT, `.previous-${new Date().toISOString().replace(/[:.]/g, "-")}`);
	const backupNotices = join(backupRoot, "THIRD-PARTY-NOTICES");
	const backupSkills = join(backupRoot, "skills");
	const backupAgents = join(backupRoot, "agents");

	async function backupIfExists(productionPath, backupPath) {
		if (existsSync(productionPath)) {
			await mkdir(backupRoot, { recursive: true });
			await rename(productionPath, backupPath);
		}
	}

	async function restoreIfBackedUp(backupPath, productionPath) {
		if (!existsSync(backupPath)) return;
		try {
			await rename(backupPath, productionPath);
		} catch {
			// best-effort restore
		}
	}

	try {
		if (existsSync(stagingNotices)) {
			await backupIfExists(productionNotices, backupNotices);
			await moveAcrossFilesystems(stagingNotices, productionNotices);
		}
		if (existsSync(stagingSkills)) {
			await backupIfExists(productionSkillsDir, backupSkills);
			await moveAcrossFilesystems(stagingSkills, productionSkillsDir);
		}
		if (existsSync(stagingAgents)) {
			await backupIfExists(productionAgentsDir, backupAgents);
			await moveAcrossFilesystems(stagingAgents, productionAgentsDir);
		}
	} catch (err) {
		warn(`Failed to commit staged content: ${err?.message ?? err}`);
		await restoreIfBackedUp(backupNotices, productionNotices);
		await restoreIfBackedUp(backupSkills, productionSkillsDir);
		await restoreIfBackedUp(backupAgents, productionAgentsDir);
		await rm(backupRoot, { recursive: true, force: true });
		await rm(stagingDir, { recursive: true, force: true });
		await rm(STAGING_PATH_FILE, { force: true });
		process.exit(1);
	}

	await rm(backupRoot, { recursive: true, force: true });
	await rm(stagingDir, { recursive: true, force: true });
	await rm(STAGING_PATH_FILE, { force: true });

	// Print a one-line summary.
	const skillCount = await readdir(productionSkillsDir).then((d) => d.length).catch(() => 0);
	const agentCount = await readdir(productionAgentsDir).then((d) => d.length).catch(() => 0);

	log(`Synced ${skillCount} skills, ${agentCount} agents into ${PACKAGE_ROOT}`);
}

main().catch((err) => {
	process.stderr.write(`[pi-compound-engineering] ERROR: ${err?.stack ?? err?.message ?? String(err)}\n`);
	process.exit(1);
});
