#!/usr/bin/env node
// @ts-check
/**
 * `postinstall` entry point. Reads the staging dir path left behind by
 * `preinstall` (`scripts/stage.mjs`) and moves the converted `skills/`,
 * `agents/`, and `THIRD-PARTY-NOTICES` into the final install dir.
 *
 * Failure modes:
 *
 * - The staging path file is missing → `preinstall` was skipped (e.g.
 *   `npm install --ignore-scripts`) or was killed mid-run. Exit 0; the
 *   extension's skipped-postinstall warning will fire on the next Pi
 *   launch and the user can recover by re-running `pi install` (the
 *   lifecycle is idempotent).
 *
 * - The staging dir no longer exists → same recovery path.
 *
 * - The commit rename fails → exit non-zero. The user gets a clear error
 *   and can retry. The previous install's `skills/`, `agents/`, and
 *   `THIRD-PARTY-NOTICES` are still on disk (they were generated by
 *   the previous install, not committed), so we back them up to
 *   `.previous-<timestamp>/` before the swap and restore on failure
 *   to avoid a half-updated install.
 */

import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rename, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_ROOT = dirname(fileURLToPath(import.meta.url)) + "/..";
const STAGING_PATH_PARENT_PREFIX = "pi-compound-engineering-staging-path-";
const STAGING_PATH_FILE_NAME = "staging-path.txt";
const RECOVERY_INSTRUCTION =
	"Re-run `pi install npm:pi-compound-engineering` (without --ignore-scripts) and restart Pi.";

function log(message) {
	process.stderr.write(`[pi-compound-engineering] ${message}\n`);
}

function warn(message) {
	process.stderr.write(`[pi-compound-engineering] WARN: ${message}\n`);
}

/**
 * Locate the most recent staging-path handoff file from the matching
 * preinstall run. The handoff file lives in a `mkdtemp`-created parent
 * dir, so the parent dir name is unpredictable. We scan `tmpdir()` for
 * any subdir matching the prefix and pick the most recently modified one.
 *
 * @returns {Promise<{ pathFile: string, parentDir: string } | null>}
 */
async function locateStagingPathFile() {
	let entries;
	try {
		entries = await readdir(tmpdir(), { withFileTypes: true });
	} catch {
		return null;
	}
	const candidates = entries.filter(
		(e) => e.isDirectory() && e.name.startsWith(STAGING_PATH_PARENT_PREFIX),
	);
	if (candidates.length === 0) return null;

	const withMtime = await Promise.all(
		candidates.map(async (entry) => {
			const parentDir = join(tmpdir(), entry.name);
			try {
				const st = await stat(parentDir);
				return { parentDir, mtimeMs: st.mtimeMs };
			} catch {
				return null;
			}
		}),
	);
	const valid = withMtime.filter((v) => v !== null);
	if (valid.length === 0) return null;
	valid.sort((a, b) => b.mtimeMs - a.mtimeMs);
	const parentDir = valid[0].parentDir;
	return { pathFile: join(parentDir, STAGING_PATH_FILE_NAME), parentDir };
}

async function readStagingPath() {
	const located = await locateStagingPathFile();
	if (!located) return null;
	try {
		const raw = await readFile(located.pathFile, "utf8");
		const trimmed = raw.trim();
		return { stagingDir: trimmed.length > 0 ? trimmed : null, ...located };
	} catch {
		return null;
	}
}

async function main() {
	const located = await readStagingPath();
	if (!located || !located.stagingDir) {
		warn(`Staging path file is missing. preinstall was skipped or killed mid-run. ${RECOVERY_INSTRUCTION}`);
		process.exit(0);
	}
	const { stagingDir, parentDir } = located;
	if (!existsSync(stagingDir)) {
		warn(`Staging dir no longer exists: ${stagingDir}. ${RECOVERY_INSTRUCTION}`);
		await rm(parentDir, { recursive: true, force: true });
		process.exit(0);
	}

	const outputDir = join(stagingDir, "output");
	if (!existsSync(outputDir)) {
		warn(`Staging output dir is missing: ${outputDir}. ${RECOVERY_INSTRUCTION}`);
		await rm(stagingDir, { recursive: true, force: true });
		await rm(parentDir, { recursive: true, force: true });
		process.exit(0);
	}

	const productionSkillsDir = join(PACKAGE_ROOT, "skills");
	const productionAgentsDir = join(PACKAGE_ROOT, "agents");
	const productionNotices = join(PACKAGE_ROOT, "THIRD-PARTY-NOTICES");

	const stagingNotices = join(outputDir, "THIRD-PARTY-NOTICES");
	const stagingSkills = join(outputDir, "skills");
	const stagingAgents = join(outputDir, "agents");

	if (!existsSync(stagingNotices)) {
		warn(`Staged THIRD-PARTY-NOTICES is missing: ${stagingNotices}.`);
	}
	if (!existsSync(stagingSkills) || !existsSync(stagingAgents)) {
		warn(`Staged skills/agents are missing in: ${outputDir}.`);
	}

	// Move the staged content into place. We rename in the order
	// THIRD-PARTY-NOTICES, skills, agents so the install dir always
	// contains a coherent state.
	//
	// For the update case, the production `skills/`, `agents/`, and
	// `THIRD-PARTY-NOTICES` may still exist from the previous version
	// (they were generated by the previous install, not committed to
	// the package). We rename the existing production content to a
	// `.previous-<timestamp>/` backup first, then atomically rename the
	// staged content into place, then remove the backup. If the rename
	// of the staged content fails for any reason, we restore the
	// previous content from the backup so the install is never left
	// in a half-updated state.
	const backupRoot = join(PACKAGE_ROOT, `.previous-${new Date().toISOString().replace(/[:.]/g, "-")}`);
	const backupNotices = join(backupRoot, "THIRD-PARTY-NOTICES");
	const backupSkills = join(backupRoot, "skills");
	const backupAgents = join(backupRoot, "agents");

	async function backupIfExists(productionPath, backupPath) {
		if (existsSync(productionPath)) {
			await mkdir(backupRoot, { recursive: true });
			await rename(productionPath, backupPath);
		}
	}

	async function restoreIfBackedUp(backupPath, productionPath) {
		if (!existsSync(backupPath)) return;
		try {
			await rename(backupPath, productionPath);
		} catch {
			// best-effort restore
		}
	}

	try {
		if (existsSync(stagingNotices)) {
			await backupIfExists(productionNotices, backupNotices);
			await rename(stagingNotices, productionNotices);
		}
		if (existsSync(stagingSkills)) {
			await backupIfExists(productionSkillsDir, backupSkills);
			await rename(stagingSkills, productionSkillsDir);
		}
		if (existsSync(stagingAgents)) {
			await backupIfExists(productionAgentsDir, backupAgents);
			await rename(stagingAgents, productionAgentsDir);
		}
	} catch (err) {
		warn(`Failed to commit staged content: ${err?.message ?? err}`);
		await restoreIfBackedUp(backupNotices, productionNotices);
		await restoreIfBackedUp(backupSkills, productionSkillsDir);
		await restoreIfBackedUp(backupAgents, productionAgentsDir);
		await rm(backupRoot, { recursive: true, force: true });
		await rm(stagingDir, { recursive: true, force: true });
		await rm(parentDir, { recursive: true, force: true });
		process.exit(1);
	}

	await rm(backupRoot, { recursive: true, force: true });
	await rm(stagingDir, { recursive: true, force: true });
	await rm(parentDir, { recursive: true, force: true });

	// Print a one-line summary.
	const skillCount = await readdir(productionSkillsDir).then((d) => d.length).catch(() => 0);
	const agentCount = await readdir(productionAgentsDir).then((d) => d.length).catch(() => 0);

	log(`Synced ${skillCount} skills, ${agentCount} agents into ${PACKAGE_ROOT}`);
}

main().catch((err) => {
	process.stderr.write(`[pi-compound-engineering] ERROR: ${err?.stack ?? err?.message ?? String(err)}\n`);
	process.exit(1);
});
